const GET_ERRORS = "GET_ERRORS";
const USER_LOADING = "USER_LOADING";
const SET_CURRENT_USER = "SET_CURRENT_USER";
const REFRESH_CURRENT_USER = "REFRESH_CURRENT_USER";
const LOGOUT_USER = "LOGOUT_USER";
const SET_POINTS = "SET_POINTS";

// Types of calls
export {
    GET_ERRORS,
    USER_LOADING,
    SET_CURRENT_USER,
    REFRESH_CURRENT_USER,
    LOGOUT_USER,
    SET_POINTS,
};
