export default {
    bottomTabNavigator : {
      Home:"Home",
      Events:"Events",
      SelfHelp:"Self-Help",
      WellnessChat:"Chat",
      Profile:"Profile",
    },
    home : {
      WelcomeNotLoggedIn:"Welcome to the wellness app",
      HeyLoggedIn:"Hey",
      Date:"Today,",
      Tip:"Tip of the day",
      FutureEvents:"Future Events",
      NewDailyMission:"Daily Mission !",
      DailyMission:"Complete your daily mission to earn points and rewards !",
      Bookings:"Bookings",
      EventsEmpty:"Nothing to display at the moment.",
      EventsFailed:"Could not load events...",
      BookingsEmpty:"Nothing to display at the moment.",
      BookingsFailed:"Could not load booking section...",
    },
    dailyMissions : {
      title: "Complete your daily mission.",
      description: "Come back everyday for new exciting missions! Earn points, collect your badges and get amazing gifts!",
      FindOwl	:"Find the owl behind one of these doors",
      HowAreYouFeeling	:"How are you feeling today ?",
      Breath	:"Take one minute to breath !",
      EatApple	:"Eat the Apple !",
      PetDog	:"Pet the Dog !",
      True	:"True",
      False	:"False",
      Gift	:"Tap the box to reveal your gift !",
      BetterLuckNextTime: "Better luck next time !",
      Done: "Done"
    },
  
    events : {
      Events:"Events",
      SearchEvents:"Search events",
      Filters:"+ filters",
      All:"All",
      ThisMonth:"This month",
      Virtual:"Virtual",
      InPerson:"In-person",
    },
  
    filterSearchPage : {
      Filters:"Filters",
      Date:"Date",
      ThisWeek:"This week",
      NextWeek:"Next week",
      ThisMonth:"This month",
      Mode:"Mode",
      Virtual:"Virtual",
      InPerson:"In-person",
      WellnessPillars:"Wellness Pillars",
      Financial:"Financial",
      Intellectual:"Intellectual",
      Social:"Social",
      Environmental:"Environmental",
      Physical:"Physical",
      Spiritual:"Spiritual",
      Emotional:"Emotional",
      ApplyFilters:"Apply Filters",
      ClearAll:"Clear All",
    },
  
    eventsDetails : {
      Financial:"Financial",
      Intellectual:"Intellectual",
      Social:"Social",
      Environmental:"Environmental",
      Physical:"Physical",
      Spiritual:"Spiritual",
      Emotional:"Emotional",
      Host:"Host",
      Registration:"Registration",
      NoRegistration:"This event doesn't require any registration",
      Details:"Additional Details",
      NoDescription:"No description provided",
      Language:"Language",
      English:"English",
      Français:"Français",
      AddToCalendar:"Add to calendar",
      Share:"Share"
    },
  
    selftHelp : {
      SelfHelp:"Self-Help",
      EmergencyContacts:"Emergency Contacts",
      Ontario:"Ontario - Good2Talk",
      Canada:"Canada - EmpowerMe",
      International:"Outside Canada - International SOS",
      ProtectionEmergency:"Protection Emergency",
      MyJournal:"My Journal",
      JournalDescription:"Write down your thoughts as they pop up, your emotions,...",
      MentalHealthSupport:"Mental Health Support",
      BookSessionCounsellor:"Book a session to talk to a counsellor or a mental health specialist.",
      SeeDoctor:"Need to see a doctor ?",
      SWHC:"Book an appointment with Student Health and Wellness Center on campus",
      WellnessNavigator:"Wellness Navigator",
      WellnessNavigatorDescription:"Don't know where to get help? Use the Wellness Navigator to navigate resources!"
    },
  
    bookSession : {
      BookSession:"Book a Session",
    },
  
    journal : {
      MyJournal:"My Journal",
      Feeling:"Feeling",
      Apply:"Apply",
      Reset:"Reset",
      StartDate:"Start date",
      EndDate:"End date",
      Search:"Search by title/entry",
      Empty:"Your journal is empty. Start writing when you're ready...",
    },

    journalEntry:{
      NewEntry:"New Entry",
      Title:"Title",
      StartWriting:"Start writing",
      Save:"Save",
    },
    loadEntry:{
      Delete:"Delete Entry",
      Title:"Title",
      Edit:"Edit",
      Save:"Save",
    },
  
    gratitude : {
      Grateful:"Grateful",
      GratefulPrompt:"Write 5 things you are grateful for today no matter how small the importance? What do you value most in life?",
      StartWriting:"Start writing",
      Save:"Save",
    },
    anxiety : {
      Stressed:"Stressed",
      StressedPrompt:"Write everything that is worrying you right now and what you can do in this moment to bring more peace?How does my stress affect my daily life?",
      StartWriting:"Start writing",
      Save:"Save",
    },
  
    angry : {
      Angry:"Angry",
      AngryPrompt:"What part about today made you angry and what were some positive aspects of your day?What are your favorite tools to utilize when you are feeling angry?",
      StartWriting:"Start writing",
      Save:"Save",
    },
  
    happy : {
      Happy:"Happy",
      HappyPrompt:"What made you smile today?How can you bring that feeling to someone else today?",
      StartWriting:"Start writing",
      Save:"Save",
    },
  
    insecure : {
      Insecure:"Insecure",
      InsecurePrompt:"What are my five best qualities? When do I feel most confident with myself? What does confidence mean to me?",
      StartWriting:"Start writing",
      Save:"Save",
    },

    lonely : {
      Lonely:"Lonely",
      LonelyPrompt:"Do you feel a certain lack of something other than company when you feel lonely? What has loneliness taught you?",
      StartWriting:"Start writing",
      Save:"Save",
    },
  
    socialIntent : {
      Chat:"Chat",
    },
  
    profile : {
      WellnessJourney:"Your Wellness Journey Starts Here.",
      Description:"Login with your university credentials and start earning points for a chance to win rewards !",
      CreateAccount:"Create an Account",
      Login:"Login",
      Welcome:"Hello,",
      Points:"Points",
      Leaderboard:"Leaderboard",
      PointSystem:"How Points Work",
      Notifications:"Notifications",
      EditProfile:"Edit Profile",
      LogOut:"Log Out",
      Language: "Language",
      ComingSoon: "Coming Soon !"
    },
  
    login : {
      Back:"Back",
      Login:"Login",
      Email:"Email",
      Password:"Password",
    },
  
    register : {
      Back:"Back",
      Register:"Register",
      FirstName:"First Name *",
      LastName:"Last Name *",
      Email:"Email *",
      Password:"Password (6-20 Characters) *",
      ConfirmPassword:"Confirm Password *",
      PhoneNumber:"Phone Number",
      SignUp:"Sign Up",
      LastNameError	:'Please provide your last name',
      FirstNameError	:'Please provide your first name',
      EmailError:'Please provide an email',
      PasswordErrorMin:'Min. password length required: 6 characters',
      PasswordErrorMax:'Max. password length permitted: 20 characters',
      PasswordError	:'Please enter a password between 6-20 characters',
      PhoneErrorMin :'Invalid phone number',
      PhoneError:'Invalid phone number',
      ConfirmPasswordError:'Please confirm your password',
      PasswordErrorMatch:'Passwords must match'
    },
  
    leaderboard : {
      Leaderboard:"Leaderboard",
      Rank:"Rank",
      User:"User",
      Badge:"Badge",
      Points:"Points",
    },
  
    pointSystem : {
      Title:"How to earn points ?",
      Explanation:"Explanation.",
      Introduction:"When exploring the Wellness App, you will find different actions helping you to earn points. From creating an avatar to sharing a wellness tip, these actions will allow you to earn points and redeem them later for rewards !",
      CreatingAccount:"Creating account",
      SharingTip:"Sharing Wellness Tip",
      ShareEvent:"Share an event",
      CreateAvatar:"Create an avatar",
      CompleteMission:"Complete daily mission",
      EnableNotifications:"Enable notifications",
      OneTime:"One-time",
      Daily:"Daily",
      Actions:"Actions.",
      ActionsList:"Here is a list of a few of the actions you can complete to earn more points !",
      Badges:"Badges.",
      BadgeDescription:"The more points you earn, the highest your rank will be ! To visualize your progress, you can simply check your badge. There are 5 different badges, here they are :",
      Bronze:"Bronze",
      Silver:"Silver",
      Gold:"Gold",
      Platinum:"Platinum",
      Diamond:"Diamond",
      Streaks:"Streaks.",
      StreaksDescription:"Everyday, you will be able to complete the 'Daily Missions'. These are short actions to complete, usually less than 20 seconds. After completing the action, you will recieve 10 points. But that's not all ! You will also receive an additional streak ! The more streak you get the greater your chance to get gifts at the end of the year !",
      Leaderboard:"Leaderboard.",
      LeaderboardDescription:"Great news ! All the users are competing together ! You can access the leaderboard to see how you're doing compared to other. Your ranking in the leaderboard is also what's going to determine to price you will get.",
      Rewards:"Rewards.",
      RewardsDescription:"Depending on your badge, you will be elligible for prices at the end of the year ! More information will be communicated to you soon...",
    },
  
    editProfile : {
      EditProfile:"Edit your profile",
      ChangeAvatar:"Change Avatar",
      FirstName:"First name.",
      LastName:"Last name.",
      PhoneNumber:"Phone Number.",
      Confirm:"Confirm",
    },
  
    createAvatar : {
      Back:"Back",
      CreateAvatar:"Create your avatar",
      Skin:"Skin",
      Eyes:"Eyes",
      Eyebrows:"Eyebrows",
      Mouth:"Mouth",
      Top:"Top",
      HairColor:"Hair Color",
      FacialHair:"Facial Hair",
      Clothes:"Clothes",
      Accessories:"Accessories",
      SaveAvatar:"Save avatar",
      NoHair:"No Hair",
      Eyepatch:"Eyepatch",
      Hat:"Hat",
      Hijab:"Hijab",
      Turban:"Turban",
      WinterHat1:"Winter Hat 1",
      WinterHat2:"Winter Hat 2",
      WinterHat3:"Winter Hat 3",
      WinterHat4:"Winter Hat 4",
      LongandBigHair:"Long and Big Hair",
      LongHairBob:"Long Hair Bob",
      LongHairBun:"Long Hair Bun",
      LongHairCurly:"Long Hair Curly",
      LongHairCurvy:"Long Hair Curvy",
      LongHairDreads:"Long Hair Dreads",
      LongHairFrida:"Long Hair Frida",
      LongHairFro:"Long Hair Fro",
      LongHairFroBand:"Long Hair Fro Band",
      SemiLongHair:"Semi Long Hair",
      LongMiaWallace:"Long Mia Wallace",
      LongHairStraight1:"Long Hair Straight 1",
      LongHairStraight2:"Long Hair Straight 2",
      LongStraightStrand:"Long Straight Strand",
      ShortDreads1:"Short Dreads 1",
      ShortDreads2:"Short Dreads 2",
      ShortHairFrizzle:"Short Hair Frizzle",
      ShortShaggyMullet:"Short Shaggy Mullet",
      ShortCurly:"Short Curly",
      ShortFlat:"Short Flat",
      ShortRound:"Short Round",
      ShortWaved:"Short Waved",
      ShortHairSides:"Short Hair Sides",
      TheCaesar:"The Caesar",
      CaesarSidePart:"Caesar Side Part",
      Blank:"Blank",
      Kurt:"Kurt",
      Prescription1:"Prescription 1",
      Prescription2:"Prescription 2",
      Round:"Round",
      Sunglasses:"Sunglasses",
      Wayfarers:"Wayfarers",
      Auburn:"Auburn",
      Black:"Black",
      Blonde:"Blonde",
      BlondeGolden:"Blonde Golden",
      Brown:"Brown",
      BrownDark:"Brown Dark",
      PastelPink:"Pastel Pink",
      Platinum:"Platinum",
      Red:"Red",
      SilverGray:"Silver Gray",
      BeardMedium:"Beard Medium",
      BeardLight:"Beard Light",
      BeardMajestic:"Beard Majestic",
      MoustacheFancy:"Moustache Fancy",
      MoustacheMagnum:"Moustache Magnum",
      BlazerShirt:"Blazer Shirt",
      BlazerSweater:"Blazer Sweater",
      CollarSweater:"Collar Sweater",
      GraphicShirt:"Graphic Shirt",
      Hoodie:"Hoodie",
      Overall:"Overall",
      ShirtCrewNeck:"Shirt Crew-Neck",
      ShirtScoopNeck:"Shirt Scoop-Neck",
      ShirtVNeck:"Shirt V-Neck",
      Close:"Close",
      Cry:"Cry",
      Default:"Default",
      Dizzy:"Dizzy",
      EyeRoll:"EyeRoll",
      Happy:"Happy",
      Hearts:"Hearts",
      Side:"Side",
      Squint:"Squint",
      Surprised:"Surprised",
      Wink:"Wink",
      WinkWacky:"WinkWacky",
      Concerned:"Concerned",
      
      Disbelief:"Disbelief",
      Eating:"Eating",
      Grimace:"Grimace",
      Sad:"Sad",
      ScreamOpen:"Scream Open",
      Serious:"Serious",
      Smile:"Smile",
      Tongue:"Tongue",
      Twinkle:"Twinkle",
      Vomit:"Vomit",
      Tanned:"Tanned",
      Yellow:"Yellow",
      Pale:"Pale",
      Light:"Light",
      DarkBrown:"Dark Brown",
      Angry:"Angry",
      AngryNatural:"Angry Natural",
      DefaultNatural:"Default Natural",
      FlatNatural:"Flat Natural",
      RaisedExcited:"Raised Excited",
      RaisedExcitedNatural:"Raised Excited Natural",
      SadConcerned:"Sad Concerned",
      SadConcernedNatural:"Sad Concerned Natural",
      UnibrowNatural:"Unibrow Natural",
      UpDown:"Up Down",
      UpDownNatural:"Up Down Natural",
    },

    language:{
      Language:'Language',
      French:"French",
      English:"English"
    }
  }