export default{
  bottomTabNavigator : {

    Home:"Maison",
    Events:"Événements",
    SelfHelp:"Bien-être",
    WellnessChat:"Clavarder",
    Profile:"Profil",
  },
 
  home : {
    WelcomeNotLoggedIn:"Bienvenue sur l'application bien-être",
    HeyLoggedIn:"Salut",
    Date:"Aujourd'hui,",
    Tip:"Conseil du jour",
    FutureEvents:"Événements futurs",
    NewDailyMission:"Nouvelle mission !",
    DailyMission:"Complétez votre mission journalière pour gagner des points et des récompenses !",
    Bookings:"Réservations",
    EventsEmpty:"Aucun événement disponible pour le moment.",
    EventsFailed:"Nous n'avons pas pu charger les événements",
    BookingsEmpty:"Aucune réservation disponible pour le moment.",
    BookingsFailed:"Nous n'avons pas pu charger les réservations",
  },
  dailyMissions : {
    title: "Complète ta mission journalière!",
    description: "Revenez tous les jours pour de nouvelles missions passionnantes ! Gagnez des points, collectez vos badges et recevez des cadeaux incroyables !",
    FindOwl	:"Trouvez le hibou derrière l'une de ces portes",
    HowAreYouFeeling	:"Comment vous sentez-vous aujourd'hui ?",
    Breath	:"Prends une minute pour respirer !",
    EatApple	:"Mange la pomme !",
    PetDog	:"Caresse le chien !",
    True	:"Vrai",
    False	:"Faux",
    Gift	:"Tape sur la boîte pour révéler ton cadeau !",
    BetterLuckNextTime: "Meilleure chance la prochaine fois !",
    Done: "Terminé"
  },

 
  events : {
 
    Events:"Événements",
    SearchEvents:"Rechercher des événements",
    Filters:"+ filtres",
    All:"Tout",
    ThisMonth:"Ce mois-ci",
    Virtual:"Virtuel",
    InPerson:"En personne",
  },
 
  filterSearchPage : {
 
    Filters:"Filtres",
    Date:"Date",
    ThisWeek:"Cette semaine",
    NextWeek:"La semaine prochaine",
    ThisMonth:"Ce mois-ci",
    Mode:"Mode",
    Virtual:"Virtuel",
    InPerson:"En personne",
    WellnessPillars:"Piliers du bien-être",
    Financial:"Financier",
    Intellectual:"Intellectuel",
    Social:"Social",
    Environmental:"Environnement",
    Physical:"Physique",
    Spiritual:"Spirituel",
    Emotional:"Émotionnel",
    ApplyFilters:"Appliquer des filtres",
    ClearAll:"Tout effacer",
  },
 
  eventsDetails : {
 
    Financial:"Financier",
    Intellectual:"Intellectuel",
    Social:"Social",
    Environmental:"Environnement",
    Physical:"Physique",
    Spiritual:"Spirituel",
    Emotional:"Émotionnel",
    Host:"Organisateur",
    Registration:"Inscription",
    NoRegistration:"Cet événement ne nécessite aucune inscription",
    Details:"Détails supplémentaires",
    NoDescription:"Aucune description fournie",
    Language:"Langue",
    English:"Anglais",
    Français:"English",
    AddToCalendar:"Ajouter au calendrier",
    Share:"Partager"
  },
 
  selftHelp : {
    SelfHelp:"Auto-assistance",
    EmergencyContacts:"Contacts d'urgence",
    Ontario:"Ontario - Good2Talk",
    Canada:"Canada - EmpowerMe",
    International:"À l'extérieur du Canada - SOS international",
    ProtectionEmergency:"Protection d'urgence",
    MyJournal:"Mon journal",
    JournalDescription:"Notez vos pensées au fur et à mesure qu'elles surgissent, vos émotions,...",
    MentalHealthSupport:"Soutien en santé mentale",
    BookSessionCounsellor:"Réservez une séance pour parler à un conseiller ou à un spécialiste de la santé mentale.",
    SeeDoctor:"Avez-vous besoin de rencontrer un médecin ?",
    SWHC:"Prenez rendez-vous avec le Centre de santé et de bien-être des étudiants sur le campus",
    WellnessNavigator:"Navigateur du mieux-être",
    WellnessNavigatorDescription:"Vous ne savez pas où trouver de l'aide ? Utilisez le navigateur du mieux-être pour trouver des ressources!"
  },
 
  bookSession : {
 
    BookSession:"Réserver une séance",
  },
 
  journal : {
 
    MyJournal:"Mon journal",
    Feeling:"Sentiment",
    Apply:"Appliquer",
    Reset:"Réinitialiser",
    StartDate:"Date de début",
    EndDate:"Date de fin",
    Search:"Recherche par titre/entrée",
    Empty:"Votre journal est vide. Commencez à écrire lorsque vous êtes prêt...",
  },

  journalEntry:{
    NewEntry:"Nouvelle entrée",
    Title:"Titre",
    StartWriting:"Commencez à écrire",
    Save:"Sauvegarder",
  },
  loadEntry:{
    Delete:"Supprimer l'entrée",
    Title:"Titre",
    Edit:"Editer",
    Save:"Sauvegarder",
  },
 
  gratitude : {
 
    Grateful:"Reconnaissant",
    GratefulPrompt:"Écrivez 5 choses pour lesquelles vous êtes reconnaissant aujourd'hui, quelle que soit leur importance ? Qu'appréciez-vous le plus dans la vie ?",
    StartWriting:"Commencez à écrire",
    Save:"sauvegarder",
  },
 
  anxiety : {
 
    Stressed:"Stressé",
    StressedPrompt:"Écrivez tout ce qui vous préoccupe en ce moment et ce que vous pouvez faire en ce moment pour apporter plus de paix ? Comment mon stress affecte-t-il ma vie quotidienne ?",
    StartWriting:"Commencez à écrire",
    Save:"sauvegarder",
  },
 
  angry : {
 
    Angry:"Fâché",
    AngryPrompt:"Quelle partie de la journée vous a mis en colère et quels ont été les aspects positifs de votre journée ? Quels sont vos outils préférés à utiliser lorsque vous vous sentez en colère ?",
    StartWriting:"Commencez à écrire",
    Save:"sauvegarder",
  },
 
  happy : {
 
    Happy:"Heureux",
    HappyPrompt:"Qu'est-ce qui vous a fait sourire aujourd'hui ? Comment pouvez-vous apporter ce sentiment à quelqu'un d'autre aujourd'hui ?",
    StartWriting:"Commencez à écrire",
    Save:"sauvegarder",
  },
 
  insecure : {
 
    Insecure:"Insécurité",
    InsecurePrompt:"Quelles sont mes cinq meilleures qualités ? Quand est-ce que je me sens le plus en confiance avec moi-même ? Que signifie la confiance pour moi ?",
    StartWriting:"Commencez à écrire",
    Save:"sauvegarder",
  },
 
  lonely : {
 
    Lonely:"Seul",
    LonelyPrompt:"Ressentez-vous un certain manque d'autre chose que de compagnie lorsque vous vous sentez seul ? Qu'est-ce que la solitude vous a appris ?",
    StartWriting:"Commencez à écrire",
    Save:"sauvegarder",
  },
 
  socialIntent : {
    Chat:"Discuter",
  },
 
  profile : {
 
    WellnessJourney:"Votre parcours de bien-être commence ici.",
    Description:"Connectez-vous avec vos identifiants universitaires et commencez à gagner des points pour avoir une chance de gagner des récompenses !",
    CreateAccount:"Créer un compte",
    Login:"Connexion",
    Welcome:"Bonjour,",
    Points:"Points",
    Leaderboard:"Classement",
    PointSystem:"Comment fonctionnent les points ?",
    Notifications:"Notifications",
    EditProfile:"Editer le profil",
    LogOut:"Se déconnecter",
    Language: "Langue",
    ComingSoon: "Bientôt disponible !"
  },
 
  login : {
 
    Back:"Retour",
    Login:"Connexion",
    Email:"E-mail",
    Password:"Mot de passe",
  },
 
  register : {
 
    Back:"Retour",
    Register:"S'inscrire",
    FirstName:"Prénom *",
    LastName:"Nom de famille *",
    Email:"E-mail *",
    Password:"Mot de passe (6-20 caractères) *",
    ConfirmPassword:"Confirmez le mot de passe *",
    PhoneNumber:"Numéro de téléphone",
    SignUp:"S'inscrire",
    LastNameError	:'Veuillez indiquer votre nom de famille',
    FirstNameError:'Veuillez indiquer votre prénom',
    EmailError	:'Veuillez fournir une adresse e-mail',
    PasswordErrorMin	:'Longueur minimale requise pour le mot de passe : 6 caractères',
    PasswordErrorMax	:'Longueur maximale autorisée du mot de passe : 20 caractères',
    PasswordError	:'Veuillez saisir un mot de passe entre 6 et 20 caractères',
    PhoneErrorMin	:'Numéro de téléphone non valide',
    PhoneError	:'Numéro de téléphone non valide',
    ConfirmPasswordError	:'Veuillez confirmer votre mot de passe',
    PasswordErrorMatch:'Les mots de passe doivent correspondre'
  },
 
  leaderboard : {
 
    Leaderboard:"Classement",
    Rank:"Rang",
    User:"Utilisateur",
    Badge:"Badge",
    Points:"Points",
  },
 
  pointSystem : {
 
    Title:"Comment gagner des points ?",
    Explanation:"Explication.",
    Introduction:"En explorant l'application Wellness, vous trouverez différentes actions vous aidant à gagner des points. De la création d'un avatar au partage d'une astuce bien-être, ces actions vous permettront de gagner des points et de les échanger plus tard contre des récompenses !",
    CreatingAccount:"La création du compte",
    SharingTip:"Partager un conseil de bien-être",
    ShareEvent:"Partager un événement",
    CreateAvatar:"Créer un avatar",
    CompleteMission:"Mission quotidienne complète",
    EnableNotifications:"Activer les notifications",
    OneTime:"Une fois",
    Daily:"du quotidien",
    Actions:"Actions.",
    ActionsList:"Voici une liste de quelques-unes des actions que vous pouvez accomplir pour gagner plus de points !",
    Badges:"Insignes.",
    BadgeDescription:"Plus vous gagnez de points, plus votre classement sera élevé ! Pour visualiser votre progression, vous pouvez simplement consulter votre badge. Il existe 5 badges différents, les voici :",
    Bronze:"Bronze",
    Silver:"Argent",
    Gold:"Or",
    Platinum:"Platine",
    Diamond:"diamant",
    Streaks:"Traces.",
    StreaksDescription:"Chaque jour, vous pourrez accomplir les 'Missions quotidiennes'. Ce sont des actions courtes à accomplir, généralement moins de 20 secondes. Après avoir terminé l'action, vous recevrez 10 points. Mais ce n'est pas tout ! Vous recevrez également une séquence supplémentaire ! Plus vous enchaînerez, plus vous aurez de chances d'obtenir des cadeaux en fin d'année !",
    Leaderboard:"Classement.",
    LeaderboardDescription:"Bonne nouvelle ! Tous les utilisateurs concourent ensemble ! Vous pouvez accéder au classement pour voir comment vous vous en sortez par rapport aux autres. Votre classement dans le classement est également ce qui déterminera le prix que vous obtiendrez.",
    Rewards:"Récompenses.",
    RewardsDescription:"En fonction de votre badge, vous serez éligible aux tarifs de fin d'année ! Plus d'informations vous seront communiquées prochainement...",
  },
 
  editProfile : {
 
    EditProfile:"Modifier votre profil",
    ChangeAvatar:"Changer d'avatar",
    FirstName:"Prénom.",
    LastName:"Nom de famille.",
    PhoneNumber:"Numéro de téléphone.",
    Confirm:"Confirmer",
  },
 
  createAvatar : {
 
    Back:"Retour",
    CreateAvatar:"Créez votre avatar",
    Skin:"Peau",
    Eyes:"Yeux",
    Eyebrows:"Les sourcils",
    Mouth:"Bouche",
    Top:"Haut",
    HairColor:"Couleur de cheveux",
    FacialHair:"Poils",
    Clothes:"Vêtements",
    Accessories:"Accessoires",
    SaveAvatar:"Enregistrer l'avatar",
    NoHair:"Pas de cheveux",
    Eyepatch:"Cache-oeil",
    Hat:"Chapeau",
    Hijab:"hijab",
    Turban:"Turban",
    WinterHat1:"Chapeau d'hiver 1",
    WinterHat2:"Chapeau d'hiver 2",
    WinterHat3:"Chapeau d'hiver 3",
    WinterHat4:"Chapeau d'hiver 4",
    LongandBigHair:"Cheveux longs et gros",
    LongHairBob:"Cheveux longs Bob",
    LongHairBun:"Chignon Cheveux Longs",
    LongHairCurly:"Cheveux longs bouclés",
    LongHairCurvy:"Cheveux longs bien roulés",
    LongHairDreads:"Dreads cheveux longs",
    LongHairFrida:"Frida cheveux longs",
    LongHairFro:"Cheveux longs",
    LongHairFroBand:"Bande de cheveux longs",
    SemiLongHair:"Cheveux mi-longs",
    LongMiaWallace:"Long Mia Wallace",
    LongHairStraight1:"Cheveux Longs Raides 1",
    LongHairStraight2:"Cheveux Longs Raides 2",
    LongStraightStrand:"Long brin droit",
    ShortDreads1:"Court Dreads 1",
    ShortDreads2:"Court Dreads 2",
    ShortHairFrizzle:"Frizz cheveux courts",
    ShortShaggyMullet:"Court Shaggy Mulet",
    ShortCurly:"Court bouclé",
    ShortFlat:"Plat court",
    ShortRound:"Tour court",
    ShortWaved:"Ondulation courte",
    ShortHairSides:"Côtés cheveux courts",
    TheCaesar:"Le César",
    CaesarSidePart:"Côté César",
    Blank:"Blanc",
    Kurt:"Kurt",
    Prescription1:"Ordonnance 1",
    Prescription2:"Ordonnance 2",
    Round:"Tour",
    Sunglasses:"Des lunettes de soleil",
    Wayfarers:"Voyageurs",
    Auburn:"Auburn",
    Black:"Le noir",
    Blonde:"Blond",
    BlondeGolden:"Blond Doré",
    Brown:"Marron",
    BrownDark:"Marron Foncé",
    PastelPink:"Rose Pastel",
    Platinum:"Platine",
    Red:"Rouge",
    SilverGray:"Gris argent",
    BeardMedium:"Barbe Moyenne",
    BeardLight:"Barbe Lumière",
    BeardMajestic:"Barbe Majestueuse",
    MoustacheFancy:"Moustache Fantaisie",
    MoustacheMagnum:"Moustache Magnum",
    BlazerShirt:"Chemise blazer",
    BlazerSweater:"Blazer Pull",
    CollarSweater:"Col Pull",
    GraphicShirt:"Chemise graphique",
    Hoodie:"Sweat à capuche",
    Overall:"Globalement",
    ShirtCrewNeck:"Chemise à col rond",
    ShirtScoopNeck:"Chemise à encolure dégagée",
    ShirtVNeck:"Chemise Col V",
    Close:"proche",
    Cry:"Cri",
    Dizzy:"Vertigineux",
    EyeRoll:"Roulement des yeux",
    Happy:"Heureux",
    Hearts:"Cœurs",
    Side:"Côté",
    Squint:"Strabisme",
    Surprised:"Surpris",
    Wink:"Clin d'œil",
    WinkWacky:"Clin d'oeilWacky",
    Concerned:"Concerné",
    Default:"Défaut",
    Disbelief:"Incrédulité",
    Eating:"En mangeant",
    Grimace:"Grimace",
    Sad:"Triste",
    ScreamOpen:"Crier ouvert",
    Serious:"Sérieuse",
    Smile:"Le sourire",
    Tongue:"Langue",
    Twinkle:"Scintillement",
    Vomit:"Vomir",
    Tanned:"Bronzé",
    Yellow:"Jaune",
    Pale:"Pâle",
    Light:"Lumière",
    DarkBrown:"Marron foncé",
    Angry:"Fâché",
    AngryNatural:"En colère Naturel",
    DefaultNatural:"Naturel par défaut",
    FlatNatural:"Plat Naturel",
    RaisedExcited:"Soulevé excité",
    RaisedExcitedNatural:"Élevé Excité Naturel",
    SadConcerned:"Triste Inquiet",
    SadConcernedNatural:"Triste Préoccupé Naturel",
    UnibrowNatural:"Unibrow Naturel",
    UpDown:"Haut Bas",
    UpDownNatural:"Haut Bas Naturel",
   },

   language:{
    Language:'Langue',
    French:"Français",
    English:"Anglais",
   }
 
 }